In [37]:
import pandas as pd
import numpy as np
from Pokemonarena.Pokemon import Pokemon
from pokemon_factory import Pokemon_Factory
from Pokemonarena.fight import Fight
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [38]:
df_pokemon = pd.read_csv('pokemon.csv')
df_mapping = pd.read_csv('pokemon_mapping.csv', encoding='cp1250', delimiter=';')

In [39]:
df_pokemon = df_pokemon.drop(['name', 'japanese_name'], axis = 1)
df_mapping = df_mapping.drop(['Englisch'], axis = 1)
df_mapping = df_mapping.dropna()
df_mapping['Id']=df_mapping['Id'].astype('int32')
df = df_pokemon.merge(df_mapping, how='inner', left_on=['pokedex_number'], right_on=['Id'])
df = df.rename(columns={"Deutsch": "name", 'sp_attack' : 'specialAttack' , 'sp_defense' : 'specialDefense'})

In [40]:
columns = ['name', 'hp', 'attack' , 'defense' , 'specialAttack','specialDefense', 'speed']
factory = Pokemon_Factory(df,columns)

In [41]:
factory = Pokemon_Factory(df,columns)
pokelist = factory.create_Pokemon_Sample(100)

In [42]:
dfs = []
for i in range(0, len(pokelist)):
    for j in range(0, len(pokelist)):
        if j != i:
            fight = Fight(pokelist[i], pokelist[j])
            dfs.append(pd.DataFrame.from_dict(fight.fight_ml()))

In [43]:
fight_df = pd.concat(dfs, axis=0)

In [44]:
X = fight_df.drop(['Gewonnen', 'name1', 'name2'], axis = 1)
y = fight_df['Gewonnen']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
model = LogisticRegression()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9057239057239057
[[1494  157]
 [ 151 1465]]
              precision    recall  f1-score   support

       False       0.91      0.90      0.91      1651
        True       0.90      0.91      0.90      1616

    accuracy                           0.91      3267
   macro avg       0.91      0.91      0.91      3267
weighted avg       0.91      0.91      0.91      3267



In [46]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9375573921028466
[[1560   91]
 [ 113 1503]]
              precision    recall  f1-score   support

       False       0.93      0.94      0.94      1651
        True       0.94      0.93      0.94      1616

    accuracy                           0.94      3267
   macro avg       0.94      0.94      0.94      3267
weighted avg       0.94      0.94      0.94      3267



In [47]:
model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.4946434037343128
[[   0 1651]
 [   0 1616]]
              precision    recall  f1-score   support

       False       0.00      0.00      0.00      1651
        True       0.49      1.00      0.66      1616

    accuracy                           0.49      3267
   macro avg       0.25      0.50      0.33      3267
weighted avg       0.24      0.49      0.33      3267

